### ISSUE TITLE
Task every two weeks being created every week

### ISSUE THREAD

**Issue by gbcox** [jsdev2015/recgtasks#35]
Here is what I have created:  *E 2 W 4 S 24/3/2016

Initially, the first task was created on 24-March, and the second task was created fine on 7-April.  However I looked this morning and discovered another task has now been created on 31-March, which is wrong.  I then deleted the task on 31-March and on the next automatic task run it was recreated.

**Comment by gbcox** [comment]
I think I may have found the issue... my computer is setup for DDMM, but Google is MMDD.  I set this app to DDMM... I'm thinking it needs to be MMDD to match Google.  I will update with results... in the meantime, don't waste your time on this until I advise.  Thanks!

**Comment by sovcik** [comment]
Thanks for letting me know. Sorry for late reply. 
Going to keep it open and wait for your reply.

**Comment by gbcox** [comment]
Closing... that was the problem...   Thanks again for a great application!

**Comment by gbcox** [comment]
Well, I was mistaken.  The issue still occurs.  It works for the first week or so, but then after that, starts scheduling every week instead of every two weeks.  I thought it might have been related somehow to the "processing week setting", which I had previously set to 3 weeks.  I set it to 2 weeks and that didn't help.  Here is what I scheduled:  *E 2 W 4 S 4/21/2016  and it created then next occurrence correctly to be 5/5/2016 - but yesterday I noticed that it now has created a task for 4/28/2016 which isn't correct.

**Comment by sovcik** [comment]
Ok, will look into it. Thanks for letting me know.

**Comment by sovcik** [comment]
I'm sorry, completely forgot about this one. Going to look at it over the weekned.

**Comment by sovcik** [comment]
Hi, I was looking into this for several hours, but I'm still unable to reproduce this issue. I'm sure it is there (few other users reported it too), but I need some help.
Could you send me your settings for the app (processing date range, date format, weeks starts on, time zone) and a log file with logging level set to "Include Developer Info".
I'm going to investigate further, but any info might help.
Thanks.
J.

**Comment by sovcik** [comment]
I have maybe found an issue - end of the next week has been calculated as midnight of the first day of the next week, which theoretically could cause the issue. But unfortunately I was unable to test as I was unable to reproduce. But I have implemented additional logging, so if you could send me a log file, then I might be able to reproduce it.

Anyway, try removing wrongly created tasks and use it for few days to see if they appear again.

Thank you and sorry for inconvenience.

**Comment by sovcik** [comment]
Closing old issue.
