### ISSUE TITLE
Recurring Tasks: Duplicating Task on following day for the following three weeks then doesn't reocurr

### ISSUE THREAD

**Issue by kevindevaux** [jsdev2015/recgtasks#38]
Hello,

I created a new recurring tasks, starting with today, then everyone 1 week on Tuesday. When I ran the process, the following week had a task reminder on Tuesday and Wednesday, same thing for the following week, however on July the task reminder is only on the Tuesday. As of July 19, there are no task reminders being repeated.

I have refreshed google (logged out, closed browser and cleared browser) and delete the task and restarted, confirming start and end dates to no success.

Thank you,

Kevin

**Comment by sovcik** [comment]
Hi Kevin, sorry to hear that.
From what I understand - the task was created to repeat every week on Tuesday and is repeating every week on Tuesday and Wednesday, correct?
Could you, please, send me the task definition? That string in task note starting with *E, or screenshot showing the task.
As for 3 weeks only - there is a setting which defines how many weeks into the future will be task created for. Default is 21 days,so if you need more, or less, you can change that in the screen Settings.
J.

**Comment by kevindevaux** [comment]
Jozef,

Thank you for your prompt reply and assistance.

I ended up, clearing the repeating tasks, remove the extension and added it
back and was able to successfully get the task to repeat for at least 8
weeks and appear only on the day I wanted them to.

Thank you for your help!

Kevin

On 22 June 2016 at 07:39, Jozef Sovcik notifications@github.com wrote:

> Hi Kevin, sorry to hear that.
> From what I understand - the task was created to repeat every week on
> Tuesday and is repeating every week on Tuesday and Wednesday, correct?
> Could you, please, send me the task definition? That string in task note
> starting with *E, or screenshot showing the task.
> As for 3 weeks only - there is a setting which defines how many weeks into
> the future will be task created for. Default is 21 days,so if you need
> more, or less, you can change that in the screen Settings.
> J.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> https://github.com/jsdev2015/recgtasks/issues/38#issuecomment-227718226,
> or mute the thread
> https://github.com/notifications/unsubscribe/ATI_k1O1QoiiboXoHEEcvuMWmyO3HDFhks5qOR7vgaJpZM4I64jd
> .

## 

Kevin Devaux

Manager of Patron Services

212 King Street West, 1st Floor

*T. *416.593.7769 Ext. 305

_F._ 416.598.9522

TSO.CA http://tso.ca/ _|_ TSOUNDCHECK.COM http://tsoundcheck.com/

@torontosymphony _|_ facebook.com/torontosymphonyorchestra

**Comment by sovcik** [comment]
Your're welcome.
J.
