### ISSUE TITLE
date shifts one day back when edited

### ISSUE THREAD

**Issue by sovcik** [jsdev2015/recgtasks#45]
User is in US-Central timezone and when he tries to modify task starting tomorrow start-date is moved back to today.

**Comment by sovcik** [comment]
This looks like a bug - UI seems to ignore user's timezone setting. Will check.

**Comment by sovcik** [comment]
I was able to reproduce the error.
If user's time zone is one day back in compare to script time zone, then when displaying date one day is subtracted.

**Comment by sovcik** [comment]
Fixed. Tested.

**Comment by markjhulme** [comment]
This is an issue for me as well. I'm in US Pacific time zone.

**Comment by sovcik** [comment]
@markjhulme If you are experiencing this issue, please, could you provide some details? I tried it with all set to your timezone and it looks OK. 
Just reminder - this is about date being shifted one day when modifying task using Manage Tasks screen.

**Comment by sovcik** [comment]
Fixed in January release
