### ISSUE TITLE
Really wish there were task group templates

### ISSUE THREAD

**Issue by xpusostomos** [jsdev2015/recgtasks#52]
I guess this isn't exactly the aim of this app, but what I really wish is that there was the ability to copy a Task group as a template to another group. I have a list of tasks that I do before I go on holidays. It's the same list I need to check off every time I go on holidays. So all I need to to copy the template list to a new list and start checking it off. It's surprising that google tasks and all the myriad of apps that integrate with it seem to lack this obvious feature.

**Comment by sovcik** [comment]
You are right in both cases:
1. yes, it would be a nice feature
1. yes, it is out of scope of this app :-)
